/*
 * Copyright (c) 2024 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef NRFS_PMIC_REQS_H
#define NRFS_PMIC_REQS_H

#include "nrfs_reqs_common.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
	NRFS_PMIC_RFFE_ON	  = NRFS_REQUEST_ID_DEF(NRFS_SERVICE_ID_PMIC, 0x01),
	NRFS_PMIC_RFFE_OFF	  = NRFS_REQUEST_ID_DEF(NRFS_SERVICE_ID_PMIC, 0x02),
	NRFS_PMIC_SIM_ON	  = NRFS_REQUEST_ID_DEF(NRFS_SERVICE_ID_PMIC, 0x03),
	NRFS_PMIC_SIM_OFF	  = NRFS_REQUEST_ID_DEF(NRFS_SERVICE_ID_PMIC, 0x04),
	NRFS_PMIC_BLE_RADIO_ON	  = NRFS_REQUEST_ID_DEF(NRFS_SERVICE_ID_PMIC, 0x05),
	NRFS_PMIC_BLE_RADIO_OFF	  = NRFS_REQUEST_ID_DEF(NRFS_SERVICE_ID_PMIC, 0x06),
	NRFS_PMIC_PWM_DEFAULT	  = NRFS_REQUEST_ID_DEF(NRFS_SERVICE_ID_PMIC, 0x07),
	NRFS_PMIC_PWM_GHOST_AVOID = NRFS_REQUEST_ID_DEF(NRFS_SERVICE_ID_PMIC, 0x08),
	NRFS_PMIC_TEST_IF	  = NRFS_REQUEST_ID_DEF(NRFS_SERVICE_ID_PMIC, 0x09),
	NRFS_PMIC_INFO		  = NRFS_REQUEST_ID_DEF(NRFS_SERVICE_ID_PMIC, 0x0A),
};

#ifdef __cplusplus
}
#endif

#endif /* NRFS_PMIC_REQS_H */
