/*
 * Copyright (c) 2025 Nordic Semiconductor ASA
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef IRONSIDE_SE_MEMORY_MAP_H_
#define IRONSIDE_SE_MEMORY_MAP_H_

#include <nrfx.h>

#ifdef __cplusplus
extern "C" {
#endif

#define IRONSIDE_SE_RADIOCORE_IPC_BUFFER_ADDRESS (0x2F88F800UL)
#define IRONSIDE_SE_RADIOCORE_IPC_BUFFER_SIZE    (128)

#define IRONSIDE_SE_RADIOCORE_EVENT_REPORT_ADDRESS (0x2F88F880UL)
#define IRONSIDE_SE_RADIOCORE_EVENT_REPORT_SIZE    (256)

#define IRONSIDE_SE_RADIOCORE_BOOT_REPORT_ADDRESS (0x2F88F980UL)
#define IRONSIDE_SE_RADIOCORE_BOOT_REPORT_SIZE    (512)

#define IRONSIDE_SE_APPLICATION_IPC_BUFFER_ADDRESS (0x2F88FB80UL)
#define IRONSIDE_SE_APPLICATION_IPC_BUFFER_SIZE    (128)

#define IRONSIDE_SE_APPLICATION_EVENT_REPORT_ADDRESS (0x2F88FC00UL)
#define IRONSIDE_SE_APPLICATION_EVENT_REPORT_SIZE    (256)

#define IRONSIDE_SE_APPLICATION_BOOT_REPORT_ADDRESS (0x2F88FD00UL)
#define IRONSIDE_SE_APPLICATION_BOOT_REPORT_SIZE    (512)

#if defined(NRF_APPLICATION)

#define IRONSIDE_SE_IPC_BUFFER_ADDRESS   IRONSIDE_SE_APPLICATION_IPC_BUFFER_ADDRESS
#define IRONSIDE_SE_IPC_BUFFER_SIZE      IRONSIDE_SE_APPLICATION_IPC_BUFFER_SIZE
#define IRONSIDE_SE_BOOT_REPORT_ADDRESS  IRONSIDE_SE_APPLICATION_BOOT_REPORT_ADDRESS
#define IRONSIDE_SE_BOOT_REPORT_SIZE     IRONSIDE_SE_APPLICATION_BOOT_REPORT_SIZE
#define IRONSIDE_SE_EVENT_REPORT_ADDRESS IRONSIDE_SE_APPLICATION_EVENT_REPORT_ADDRESS
#define IRONSIDE_SE_EVENT_REPORT_SIZE    IRONSIDE_SE_APPLICATION_EVENT_REPORT_SIZE
#define IRONSIDE_SE_BOOT_REPORT_ADDRESS  IRONSIDE_SE_APPLICATION_BOOT_REPORT_ADDRESS
#define IRONSIDE_SE_BOOT_REPORT_SIZE     IRONSIDE_SE_APPLICATION_BOOT_REPORT_SIZE

#elif defined(NRF_RADIOCORE)

#define IRONSIDE_SE_IPC_BUFFER_ADDRESS   IRONSIDE_SE_RADIOCORE_IPC_BUFFER_ADDRESS
#define IRONSIDE_SE_IPC_BUFFER_SIZE      IRONSIDE_SE_RADIOCORE_IPC_BUFFER_SIZE
#define IRONSIDE_SE_BOOT_REPORT_ADDRESS  IRONSIDE_SE_RADIOCORE_BOOT_REPORT_ADDRESS
#define IRONSIDE_SE_BOOT_REPORT_SIZE     IRONSIDE_SE_RADIOCORE_BOOT_REPORT_SIZE
#define IRONSIDE_SE_EVENT_REPORT_ADDRESS IRONSIDE_SE_RADIOCORE_EVENT_REPORT_ADDRESS
#define IRONSIDE_SE_EVENT_REPORT_SIZE    IRONSIDE_SE_RADIOCORE_EVENT_REPORT_SIZE
#define IRONSIDE_SE_BOOT_REPORT_ADDRESS  IRONSIDE_SE_RADIOCORE_BOOT_REPORT_ADDRESS
#define IRONSIDE_SE_BOOT_REPORT_SIZE     IRONSIDE_SE_RADIOCORE_BOOT_REPORT_SIZE

#endif

#define IRONSIDE_SE_UPDATE_BLOB_SIZE (160 * 1024)

#if defined(NRF54H20_XXAA)

#define IRONSIDE_SE_UPDATE_MIN_ADDRESS (0x0E100000)
#define IRONSIDE_SE_UPDATE_MAX_ADDRESS (0x0E200000 - IRONSIDE_SE_UPDATE_BLOB_SIZE)

#elif defined(NRF9230_ENGB_XXAA)

#define IRONSIDE_SE_UPDATE_MIN_ADDRESS (0x0E600000)
#define IRONSIDE_SE_UPDATE_MAX_ADDRESS (0x0E72F000 - IRONSIDE_SE_UPDATE_BLOB_SIZE)

#endif

#ifdef __cplusplus
}
#endif
#endif /* IRONSIDE_SE_MEMORY_MAP_H_ */
